export default {
  "minecraft:apple": { texture: "textures/items/apple" },
  "minecraft:breeze_rod": { texture: "textures/items/breeze_rod" },
  "minecraft:end_crystal": { texture: "textures/items/end_crystal" },
  "minecraft:glow_berries": { texture: "textures/items/glow_berries" },
  "minecraft:ominous_trial_key": { texture: "textures/items/ominous_trial_key" },
  "minecraft:ominous_vault": { texture: "textures/blocks/vault_side_on_ominous" },
  "minecraft:wind_charge": { texture: "textures/items/wind_charge" },

  // spears
  "minecraft:copper_spear": { texture: "textures/items/spear/copper_spear" },
  "minecraft:diamond_spear": { texture: "textures/items/spear/diamond_spear" },
  "minecraft:golden_spear": { texture: "textures/items/spear/gold_spear" },
  "minecraft:iron_spear": { texture: "textures/items/spear/iron_spear" },
  "minecraft:netherite_spear": { texture: "textures/items/spear/netherite_spear" },
  "minecraft:stone_spear": { texture: "textures/items/spear/stone_spear" },
  "minecraft:wooden_spear": { texture: "textures/items/spear/wood_spear" },

  // bundles
  "minecraft:bundle": { texture: "textures/items/bundle" },
  "minecraft:black_bundle": { texture: "textures/items/bundle_black" },
  "minecraft:blue_bundle": { texture: "textures/items/bundle_blue" },
  "minecraft:brown_bundle": { texture: "textures/items/bundle_brown" },
  "minecraft:cyan_bundle": { texture: "textures/items/bundle_cyan" },
  "minecraft:gray_bundle": { texture: "textures/items/bundle_gray" },
  "minecraft:green_bundle": { texture: "textures/items/bundle_green" },
  "minecraft:light_blue_bundle": { texture: "textures/items/bundle_light_blue" },
  "minecraft:light_gray_bundle": { texture: "textures/items/bundle_light_gray" },
  "minecraft:lime_bundle": { texture: "textures/items/bundle_lime" },
  "minecraft:magenta_bundle": { texture: "textures/items/bundle_magenta" },
  "minecraft:open_bundle": { texture: "textures/items/bundle_open" },
  "minecraft:orange_bundle": { texture: "textures/items/bundle_orange" },
  "minecraft:pink_bundle": { texture: "textures/items/bundle_pink" },
  "minecraft:purple_bundle": { texture: "textures/items/bundle_purple" },
  "minecraft:red_bundle": { texture: "textures/items/bundle_red" },
  "minecraft:white_bundle": { texture: "textures/items/bundle_white" },
  "minecraft:yellow_bundle": { texture: "textures/items/bundle_yellow" },
};
