export default {
  anvil: { texture: "minecraft:anvil" },
  blockExplosion: { texture: "minecraft:bed" },
  contact: { texture: "minecraft:sweet_berry_bush" },
  drowning: { texture: "textures/ui/bubble" },
  entityAttack: { texture: "minecraft:iron_axe" },
  entityExplosion: { texture: "minecraft:tnt" },
  fall: { texture: "textures/ui/empty_armor_slot_boots" },
  fire: { texture: "minecraft:campfire (animated)" },
  fireTick: { texture: "minecraft:fire" },
  fireworks: { texture: "minecraft:firework_rocket" },
  flyIntoWall: { texture: "minecraft:elytra" },
  freezing: { texture: "minecraft:powder_snow" },
  lava: { texture: "minecraft:lava" },
  lightning: { texture: "minecraft:lightning_rod" },
  maceSmash: { texture: "minecraft:mace" },
  magic: { texture: "minecraft:potion" },
  magma: { texture: "minecraft:magma" },
  projectile: { texture: "minecraft:arrow" },
  ramAttack: { texture: "minecraft:goat_spawn_egg" },
  sonicBoom: { texture: "minecraft:warden_spawn_egg" },
  stalactite: { texture: "minecraft:pointed_dripstone" },
  stalagmite: { texture: "minecraft:pointed_dripstone" },
  starve: { texture: "textures/ui/hunger_effect" },
  suffocation: { texture: "minecraft:sand" },
  temperature: { texture: "textures/environment/sun_vv" },
  thorns: { texture: "minecraft:rose_bush" },
  void: { texture: "textures/ui/Black" },
  wither: { texture: "minecraft:wither_rose" },
} as const;
